# Generated by Django 5.1.5 on 2025-01-26 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('Estrela', 'ESTRELA'), ('Galáxia', 'GALÁXIA'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
